### ISSUE TITLE
Netlify-deployed site shows 404 on the main page

### ISSUE THREAD

**Issue by fyodorio** [dofbi/astro-simple-blog-theme#1]
Thanks for the great starter theme 👍

When I try to deploy it to netlify using default flow from the astro.build site,

<img width="422" alt="Screenshot 2022-08-24 at 12 48 46" src="https://user-images.githubusercontent.com/19417873/186361901-453d4734-de67-45d8-84f7-fe072a4d8e23.png">

the deployed main page doesn't show the list of posts. Returns 404 error.

<img width="1260" alt="Screenshot 2022-08-24 at 12 47 37" src="https://user-images.githubusercontent.com/19417873/186362122-29cb5639-6c2f-40f2-a92c-cd72730df5cc.png">

Tried locally — works good (including static build serving). Some weird deployment flow issue I guess.

**Comment by dofbi** [comment]
Hello @fyodorio 
Thanks for your motivation message I just click the button made new deployment on netlify this is the link https://willowy-fudge-11c618.netlify.app/
![Capture d’écran du 2022-08-25 09-06-45](https://user-images.githubusercontent.com/84446/186623992-7a23eb42-d20b-4d79-96bd-40c7299ac2bb.png)
It's look like, try again
may be some issue on netlify

**Comment by fyodorio** [comment]
Ah, OK, if it doesn't reproduce — feel free to close it please, and thanks for checking. Anyway, will either try again (pushing to `main` doesn't help) or will reconfigure the deployment from the opposite site. Or will use Vercel 😄
